name: Code CI
on: [push, pull_request]
jobs:
  Build_Release:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependancies
        run: sudo apt-get install -y texlive-latex-base
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: make -C ${{ github.event.repository.name }}
      - name: Store
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.event.repository.name }}/*.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}/*.pdf