name: Code CI
on: [push, pull_request]
jobs:
  Build_Release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run:  echo ./${{ github.event.repository.name }}:/source
      - name: Build
        run: |
          docker run \
          -v ./${{ github.event.repository.name }}:/source \
          ghcr.io/xu-cheng/texlive-full:latest \
          /bin/bash -c "make -C /source/"
      - name: Store
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.event.repository.name }}/*.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}/*.pdf